server:
  port: 7000

spring:
  config:
    activate:
      on-profile: profile-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://swyg9.cp8aui86i2il.ap-northeast-2.rds.amazonaws.com:3306/stag
    username: sulbin
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update

crawling:
  url: https://www.molit.go.kr/USR/NEWS/m_71/lst.jsp?search_section=p_sec_2