server:
  port: 8000

spring:
  config:
    activate:
      on-profile: profile-prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://swyg9.cp8aui86i2il.ap-northeast-2.rds.amazonaws.com:3306/prod
    username: sulbin
    password: 12341234
