server:
  port: 8000

spring:
  config:
    activate:
      on-profile: profile-prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://swyg9.cp8aui86i2il.ap-northeast-2.rds.amazonaws.com:3306/prod
    username: sulbin
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  date:
    web:
      pageable:
        default-page-size: 10
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ghksgml05555@gmail.com
    password: ejms dzjo xzpd dvwq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 180000 #3분
  data:
    redis:
      host: localhost
      port: 6379


jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

crawling:
  url: https://www.molit.go.kr/USR/NEWS/m_71/lst.jsp?search_section=p_sec_2&search=&search_gubun=1&search_gubun1=all&srch_usr_titl=Y&srch_usr_ctnt=&psize=10&search_regdate_s=2023-02-27&search_regdate_e=&srch_cate=&srch_dept_nm=&search_kind=&search_gbn=&lst_gbn=T&lcmspage=

cloud:
  aws:
    s3:
      bucket: swyg-bucket
    credentials:
      access-key: AKIAXYKJS7QBIFKGKRAE
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

springdoc:
  show-login-endpoint: true